const markets=[['NIFTY 50','25,118.95','+0.82%'],['SENSEX','82,365.77','+0.67%'],['S&P 500','6,481.40','+0.21%'],['NASDAQ','21,590.14','-0.18%'],['NIKKEI','43,812.70','+1.10%'],['DAX','24,921.10','+0.44%']]
const movers=[['Reliance Industries','₹1,418.30','+2.84%'],['Tata Motors','₹684.75','+2.31%'],['Infosys','₹1,492.20','+1.72%'],['HDFC Bank','₹1,942.60','-0.84%'],['ICICI Bank','₹1,431.40','+0.61%']]

export default function Home(){return <main className="min-h-screen flex">
<aside className="w-64 border-r border-white/5 p-5 hidden lg:block"><div className="text-xl font-bold tracking-tight mb-10">◈ Market<span className="text-cyan-400">OS</span></div><nav className="space-y-2 text-sm text-slate-400">{['Overview','Markets','Screener','Watchlist','Portfolio','News','AI Research','Alerts'].map((x,i)=><div className={`px-3 py-2.5 rounded-lg ${i===0?'bg-white/8 text-white':''}`} key={x}>{x}</div>)}</nav><div className="mt-10 p-4 rounded-xl glass"><div className="text-xs text-slate-500">AI MARKET COPILOT</div><p className="text-sm mt-2 text-slate-300">Ask why markets moved, compare companies, or scan for opportunities.</p><button className="mt-3 w-full rounded-lg bg-cyan-400 text-black py-2 text-sm font-semibold">Open AI</button></div></aside>
<section className="flex-1 p-5 md:p-8 max-w-[1600px] mx-auto w-full"><header className="flex flex-col md:flex-row md:items-center gap-4 justify-between mb-7"><div><div className="text-sm text-cyan-400 font-medium">FRIDAY · AUG 28, 2026</div><h1 className="text-3xl md:text-4xl font-bold mt-1">Good evening, market watcher.</h1><p className="text-slate-500 mt-1">Everything moving the world’s markets, in one place.</p></div><div className="flex gap-2"><input placeholder="Search stocks, ETFs, markets..." className="w-64 bg-white/5 border border-white/8 rounded-xl px-4 py-2.5 outline-none focus:border-cyan-400/50"/><button className="glass px-4 rounded-xl">⌘K</button></div></header>
<div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3 mb-7">{markets.map(([n,v,c])=><div className="glass rounded-xl p-4" key={n}><div className="text-xs text-slate-500">{n}</div><div className="font-semibold mt-2">{v}</div><div className={`text-xs mt-1 ${c.startsWith('-')?'text-red-400':'text-emerald-400'}`}>{c}</div></div>)}</div>
<div className="grid xl:grid-cols-[1.5fr_1fr] gap-5"><div className="glass rounded-2xl p-5 min-h-[390px]"><div className="flex justify-between"><div><h2 className="font-semibold text-lg">Global Market Pulse</h2><p className="text-sm text-slate-500">Major indices · live feed will connect here</p></div><button className="text-sm text-cyan-400">View all →</button></div><div className="h-64 mt-7 rounded-xl bg-gradient-to-b from-cyan-400/8 to-transparent border-b border-white/5 relative overflow-hidden"><svg viewBox="0 0 900 260" className="w-full h-full"><polyline fill="none" stroke="currentColor" strokeWidth="3" className="text-cyan-400" points="0,205 55,190 95,198 150,150 205,170 260,120 310,135 365,90 420,115 480,70 540,92 600,45 660,62 720,32 780,54 840,20 900,38"/></svg></div><div className="flex justify-between text-xs text-slate-600 mt-2"><span>9:15</span><span>11:00</span><span>13:00</span><span>15:00</span><span>Close</span></div></div>
<div className="glass rounded-2xl p-5"><div className="flex justify-between items-center"><div><h2 className="font-semibold text-lg">Top Movers</h2><p className="text-sm text-slate-500">Today’s notable moves</p></div><span className="text-xs text-slate-500">INDIA</span></div><div className="mt-5 space-y-1">{movers.map(([n,v,c])=><div className="flex items-center justify-between p-3 rounded-xl hover:bg-white/5" key={n}><div><div className="text-sm font-medium">{n}</div><div className="text-xs text-slate-500">NSE · Equity</div></div><div className="text-right"><div className="text-sm">{v}</div><div className={`text-xs ${c.startsWith('-')?'text-red-400':'text-emerald-400'}`}>{c}</div></div></div>)}</div></div></div>
<div className="grid md:grid-cols-3 gap-5 mt-5"><div className="glass rounded-2xl p-5"><div className="text-xs text-cyan-400">AI BRIEF</div><h3 className="font-semibold mt-2">What matters today?</h3><p className="text-sm text-slate-400 mt-2">AI-generated market context will appear here once live data and news tools are connected.</p></div><div className="glass rounded-2xl p-5"><div className="text-xs text-cyan-400">WATCHLIST</div><h3 className="font-semibold mt-2">Your stocks</h3><p className="text-sm text-slate-400 mt-2">Add companies to follow prices, news, fundamentals and AI alerts.</p></div><div className="glass rounded-2xl p-5"><div className="text-xs text-cyan-400">SCREENER</div><h3 className="font-semibold mt-2">Find something interesting</h3><p className="text-sm text-slate-400 mt-2">Scan thousands of assets using fundamentals, technicals and custom AI criteria.</p></div></div>
</section></main>}
