'use client'

import {ReactNode,useState} from 'react'

const nav=[['⌂','Overview','/'],['◫','Markets','/markets'],['⌕','Screener','/screener'],['★','Watchlist','/watchlist'],['◈','Portfolio','/portfolio'],['📰','News','/news'],['✦','AI Research','/research'],['⚡','Alerts','/alerts'],['◉','AI Copilot','/ai']]

export default function AppShell({children}:{children:ReactNode}){
 const [mobile,setMobile]=useState(false)
 return <div className="min-h-screen bg-[#070a0f] text-white"><header className="lg:hidden sticky top-0 z-30 border-b border-white/10 bg-[#070a0f]/90 backdrop-blur-xl px-4 py-3 flex items-center justify-between"><a href="/" className="font-bold">◈ Market<span className="text-cyan-400">OS</span></a><button onClick={()=>setMobile(!mobile)} className="rounded-lg bg-white/5 px-3 py-2">☰</button></header>{mobile&&<div className="lg:hidden fixed inset-0 z-40 bg-[#070a0f] p-5"><div className="flex justify-between mb-8"><div className="font-bold text-xl">◈ Market<span className="text-cyan-400">OS</span></div><button onClick={()=>setMobile(false)}>✕</button></div><nav className="space-y-2">{nav.map(([icon,label,url])=><a onClick={()=>setMobile(false)} className="block rounded-xl px-4 py-3 hover:bg-white/5" href={url} key={label}>{icon} <span className="ml-3">{label}</span></a>)}</nav></div>}<div className="flex"><aside className="hidden lg:block w-64 shrink-0 border-r border-white/5 min-h-screen p-5 sticky top-0 h-screen"><a href="/" className="text-xl font-bold tracking-tight">◈ Market<span className="text-cyan-400">OS</span></a><div className="text-[10px] text-slate-600 mt-2 tracking-widest">MARKET INTELLIGENCE</div><nav className="mt-10 space-y-1">{nav.map(([icon,label,url],i)=><a href={url} className={`flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm ${i===0?'bg-white/8 text-white':'text-slate-400 hover:bg-white/5 hover:text-white'}`} key={label}><span className="w-5">{icon}</span>{label}</a>)}</nav><div className="glass rounded-2xl p-4 mt-10"><div className="text-[10px] text-cyan-400 tracking-widest">AI COPILOT</div><p className="text-xs text-slate-400 mt-2 leading-5">Research markets, compare stocks and explore the demo universe.</p><a href="/ai" className="block text-center mt-3 rounded-xl bg-cyan-400 text-black py-2 text-xs font-bold">Open AI</a></div><div className="mt-8 text-[10px] text-slate-600">DATA MODE</div><div className="mt-1 text-xs text-emerald-400">● DEMO / LIVE OFF</div></aside><div className="flex-1 min-w-0">{children}</div></div></div>
}
